# Generated by Django 5.1.6 on 2025-10-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В процессе'), ('ended', 'Завершен')], default='in_progress', max_length=15),
        ),
    ]
