# Generated by Django 5.1.6 on 2025-10-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_visit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_images/'),
        ),
    ]
