# Generated by Django 5.1.6 on 2025-10-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='plain_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
