# Generated by Django 5.1.6 on 2025-11-01 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_reception'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reception',
            name='password',
        ),
    ]
