# Generated by Django 5.0 on 2025-11-25 14:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_reception_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
